name: mailcheckai
description: API Wrapper for mailcheck.ai
version: 1.0.1
repository: https://github.com/Myzel394/dart-mailcheckai

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {http: ^0.13.5}
